`timescale 1ns / 1ps

module tb_fnd_sim();


        reg clk;
        reg reset;
        reg [7:0] a;
        reg [7:0] b;
        wire [7:0] fnd_data;
        wire [3:0] fnd_digit;
        

    top_adder dut(
    
    .clk(clk),
    .reset(reset),
    .a(a),
    .b(b),
    .fnd_digit(fnd_digit),
    .fnd_data(fnd_data)
    
);
    
    always #5 clk = ~clk;

    initial begin
        
        #0;
        clk = 0;
        reset = 1;
        a = 0; 
        b = 0;  
        #20;
        reset = 0;
        a = 1;
        b = 0;

        #20;
        reset = 0;
        a = 2;
        b = 0;

        #20;
        reset = 0;
        a = 3;
        b = 0;

        #20;
        reset = 0;
        a = 4;
        b = 0;

        #20;
        reset = 0;
        a = 5;
        b = 0;

        #20;
        reset = 0;
        a = 6;
        b = 0;

        #20;
        reset = 0;
        a = 7;
        b = 0;

        #20;
        reset = 0;
        a = 8;
        b = 0;

        #20;
        reset = 0;
        a = 9;
        b = 0;

        a= 255;
        b= 255;
        #1000;
        $stop;

        
    

        
         
    end
     
endmodule
