`timescale 1ns / 1ps



module tb_fork_join();


    initial begin
        #1 $display("%t : start fork - join", $time);

        fork
            //task A
            #10 A_thread();
            //task B
            #20 B_thread();
            //task C
            #15 C_thread();


        join

        #10 $display("%t : end fork - join", $time);
    end

    task A_thread();
        $display("%t: A thread", $time);
    endtask

    task B_thread();
        $display("%t: B thread", $time);
    endtask

    task C_thread();
        $display("%t: B thread", $time);
    endtask
endmodule



initial begin
    #1 $display("%t : start fork - join", $time);

    fork
        
    join_any
end
